version: '2'

services:
    http-worker-xdebug:
        image: nginx:alpine
        volumes:
            - ./.docker/nginx@1.15/config/options.conf:/etc/nginx/conf.d/000-options.conf
            - ./.docker/nginx@1.15/config/vhost-xdebug.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - cache:/var/www/html/var/cache:ro
            - assets:/var/www/html/public/bundles:ro
        restart: on-failure
        ports:
            - ${HTTP_XDEBUG_PORT}:80
        depends_on:
            - fpm-xdebug
    fpm-xdebug:
        image: kiboko/php:7.2-fpm-xdebug-orocommerce-ee-3.1-postgresql
        user: docker:docker
        volumes:
            - ./:/var/www/html
            - .docker/fpm-xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - cache:/var/www/html/var/cache
            - assets:/var/www/html/public/bundles
        environment:
            - "I_AM_DEVELOPER_DISABLE_INDEX_IP_CHECK="
        restart: on-failure
    sh-xdebug:
        image: kiboko/php:7.2-cli-xdebug-orocommerce-ee-3.1-postgresql
        user: docker:docker
        volumes:
            - $HOME/.ssh:/opt/docker/.ssh:cached
            - ./:/var/www/html
            - cache:/var/www/html/var/cache
            - assets:/var/www/html/public/bundles
            - composer:/opt/docker/.composer/
        environment:
            - COMPOSER_AUTH
            - COMPOSER_PROCESS_TIMEOUT
        command: [ "sleep", "31536000" ]
        restart: "always"
volumes:
    backups:
        driver: local
    database:
        driver: local
    elasticsearch:
        driver: local
    composer:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=2048m,uid=1000,gid=1000"
    assets:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=2048m,uid=1000,gid=1000"
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=2048m,uid=1000,gid=1000"
